/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MoodInputRouteImport } from './routes/mood-input'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RestaurantIdRouteImport } from './routes/restaurant.$id'
import { Route as DrinksIdRouteImport } from './routes/drinks.$id'
import { Route as ApiMatchDcpCocktailRouteImport } from './routes/api/match-dcp-cocktail'
import { Route as ApiGenerateCocktailImageRouteImport } from './routes/api/generate-cocktail-image'
import { Route as ApiGenerateCocktailRouteImport } from './routes/api/generate-cocktail'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MoodInputRoute = MoodInputRouteImport.update({
  id: '/mood-input',
  path: '/mood-input',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantIdRoute = RestaurantIdRouteImport.update({
  id: '/restaurant/$id',
  path: '/restaurant/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DrinksIdRoute = DrinksIdRouteImport.update({
  id: '/drinks/$id',
  path: '/drinks/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMatchDcpCocktailRoute = ApiMatchDcpCocktailRouteImport.update({
  id: '/api/match-dcp-cocktail',
  path: '/api/match-dcp-cocktail',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateCocktailImageRoute =
  ApiGenerateCocktailImageRouteImport.update({
    id: '/api/generate-cocktail-image',
    path: '/api/generate-cocktail-image',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGenerateCocktailRoute = ApiGenerateCocktailRouteImport.update({
  id: '/api/generate-cocktail',
  path: '/api/generate-cocktail',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/gallery': typeof GalleryRoute
  '/mood-input': typeof MoodInputRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/generate-cocktail': typeof ApiGenerateCocktailRoute
  '/api/generate-cocktail-image': typeof ApiGenerateCocktailImageRoute
  '/api/match-dcp-cocktail': typeof ApiMatchDcpCocktailRoute
  '/drinks/$id': typeof DrinksIdRoute
  '/restaurant/$id': typeof RestaurantIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/gallery': typeof GalleryRoute
  '/mood-input': typeof MoodInputRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/generate-cocktail': typeof ApiGenerateCocktailRoute
  '/api/generate-cocktail-image': typeof ApiGenerateCocktailImageRoute
  '/api/match-dcp-cocktail': typeof ApiMatchDcpCocktailRoute
  '/drinks/$id': typeof DrinksIdRoute
  '/restaurant/$id': typeof RestaurantIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/gallery': typeof GalleryRoute
  '/mood-input': typeof MoodInputRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/generate-cocktail': typeof ApiGenerateCocktailRoute
  '/api/generate-cocktail-image': typeof ApiGenerateCocktailImageRoute
  '/api/match-dcp-cocktail': typeof ApiMatchDcpCocktailRoute
  '/drinks/$id': typeof DrinksIdRoute
  '/restaurant/$id': typeof RestaurantIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/gallery'
    | '/mood-input'
    | '/sitemap.xml'
    | '/api/generate-cocktail'
    | '/api/generate-cocktail-image'
    | '/api/match-dcp-cocktail'
    | '/drinks/$id'
    | '/restaurant/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/gallery'
    | '/mood-input'
    | '/sitemap.xml'
    | '/api/generate-cocktail'
    | '/api/generate-cocktail-image'
    | '/api/match-dcp-cocktail'
    | '/drinks/$id'
    | '/restaurant/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/gallery'
    | '/mood-input'
    | '/sitemap.xml'
    | '/api/generate-cocktail'
    | '/api/generate-cocktail-image'
    | '/api/match-dcp-cocktail'
    | '/drinks/$id'
    | '/restaurant/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  GalleryRoute: typeof GalleryRoute
  MoodInputRoute: typeof MoodInputRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiGenerateCocktailRoute: typeof ApiGenerateCocktailRoute
  ApiGenerateCocktailImageRoute: typeof ApiGenerateCocktailImageRoute
  ApiMatchDcpCocktailRoute: typeof ApiMatchDcpCocktailRoute
  DrinksIdRoute: typeof DrinksIdRoute
  RestaurantIdRoute: typeof RestaurantIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mood-input': {
      id: '/mood-input'
      path: '/mood-input'
      fullPath: '/mood-input'
      preLoaderRoute: typeof MoodInputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/$id': {
      id: '/restaurant/$id'
      path: '/restaurant/$id'
      fullPath: '/restaurant/$id'
      preLoaderRoute: typeof RestaurantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drinks/$id': {
      id: '/drinks/$id'
      path: '/drinks/$id'
      fullPath: '/drinks/$id'
      preLoaderRoute: typeof DrinksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/match-dcp-cocktail': {
      id: '/api/match-dcp-cocktail'
      path: '/api/match-dcp-cocktail'
      fullPath: '/api/match-dcp-cocktail'
      preLoaderRoute: typeof ApiMatchDcpCocktailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-cocktail-image': {
      id: '/api/generate-cocktail-image'
      path: '/api/generate-cocktail-image'
      fullPath: '/api/generate-cocktail-image'
      preLoaderRoute: typeof ApiGenerateCocktailImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-cocktail': {
      id: '/api/generate-cocktail'
      path: '/api/generate-cocktail'
      fullPath: '/api/generate-cocktail'
      preLoaderRoute: typeof ApiGenerateCocktailRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  GalleryRoute: GalleryRoute,
  MoodInputRoute: MoodInputRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiGenerateCocktailRoute: ApiGenerateCocktailRoute,
  ApiGenerateCocktailImageRoute: ApiGenerateCocktailImageRoute,
  ApiMatchDcpCocktailRoute: ApiMatchDcpCocktailRoute,
  DrinksIdRoute: DrinksIdRoute,
  RestaurantIdRoute: RestaurantIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
