/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MoodInputRouteImport } from './routes/mood-input'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultIdRouteImport } from './routes/result.$id'
import { Route as ApiGenerateCocktailImageRouteImport } from './routes/api/generate-cocktail-image'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MoodInputRoute = MoodInputRouteImport.update({
  id: '/mood-input',
  path: '/mood-input',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultIdRoute = ResultIdRouteImport.update({
  id: '/result/$id',
  path: '/result/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateCocktailImageRoute =
  ApiGenerateCocktailImageRouteImport.update({
    id: '/api/generate-cocktail-image',
    path: '/api/generate-cocktail-image',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/mood-input': typeof MoodInputRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/generate-cocktail-image': typeof ApiGenerateCocktailImageRoute
  '/result/$id': typeof ResultIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/mood-input': typeof MoodInputRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/generate-cocktail-image': typeof ApiGenerateCocktailImageRoute
  '/result/$id': typeof ResultIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/mood-input': typeof MoodInputRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/generate-cocktail-image': typeof ApiGenerateCocktailImageRoute
  '/result/$id': typeof ResultIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gallery'
    | '/mood-input'
    | '/sitemap.xml'
    | '/api/generate-cocktail-image'
    | '/result/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gallery'
    | '/mood-input'
    | '/sitemap.xml'
    | '/api/generate-cocktail-image'
    | '/result/$id'
  id:
    | '__root__'
    | '/'
    | '/gallery'
    | '/mood-input'
    | '/sitemap.xml'
    | '/api/generate-cocktail-image'
    | '/result/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GalleryRoute: typeof GalleryRoute
  MoodInputRoute: typeof MoodInputRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiGenerateCocktailImageRoute: typeof ApiGenerateCocktailImageRoute
  ResultIdRoute: typeof ResultIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mood-input': {
      id: '/mood-input'
      path: '/mood-input'
      fullPath: '/mood-input'
      preLoaderRoute: typeof MoodInputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/$id': {
      id: '/result/$id'
      path: '/result/$id'
      fullPath: '/result/$id'
      preLoaderRoute: typeof ResultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-cocktail-image': {
      id: '/api/generate-cocktail-image'
      path: '/api/generate-cocktail-image'
      fullPath: '/api/generate-cocktail-image'
      preLoaderRoute: typeof ApiGenerateCocktailImageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GalleryRoute: GalleryRoute,
  MoodInputRoute: MoodInputRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiGenerateCocktailImageRoute: ApiGenerateCocktailImageRoute,
  ResultIdRoute: ResultIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
