/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MoodInputRouteImport } from './routes/mood-input'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RestaurantsDoubleChickenPleaseRouteImport } from './routes/restaurants.double-chicken-please'
import { Route as RestaurantIdRouteImport } from './routes/restaurant.$id'
import { Route as ManagePrivateTokenRouteImport } from './routes/manage.$privateToken'
import { Route as GuidesMoodCocktailRecipesRouteImport } from './routes/guides.mood-cocktail-recipes'
import { Route as DrinksIdRouteImport } from './routes/drinks.$id'
import { Route as ApiMenuMatchRouteImport } from './routes/api/menu-match'
import { Route as ApiGenerateCocktailImageRouteImport } from './routes/api/generate-cocktail-image'
import { Route as ApiGenerateCocktailRouteImport } from './routes/api/generate-cocktail'
import { Route as MMerchantSlugMenuSlugRouteImport } from './routes/m.$merchantSlug.$menuSlug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MoodInputRoute = MoodInputRouteImport.update({
  id: '/mood-input',
  path: '/mood-input',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsDoubleChickenPleaseRoute =
  RestaurantsDoubleChickenPleaseRouteImport.update({
    id: '/restaurants/double-chicken-please',
    path: '/restaurants/double-chicken-please',
    getParentRoute: () => rootRouteImport,
  } as any)
const RestaurantIdRoute = RestaurantIdRouteImport.update({
  id: '/restaurant/$id',
  path: '/restaurant/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagePrivateTokenRoute = ManagePrivateTokenRouteImport.update({
  id: '/manage/$privateToken',
  path: '/manage/$privateToken',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesMoodCocktailRecipesRoute =
  GuidesMoodCocktailRecipesRouteImport.update({
    id: '/guides/mood-cocktail-recipes',
    path: '/guides/mood-cocktail-recipes',
    getParentRoute: () => rootRouteImport,
  } as any)
const DrinksIdRoute = DrinksIdRouteImport.update({
  id: '/drinks/$id',
  path: '/drinks/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMenuMatchRoute = ApiMenuMatchRouteImport.update({
  id: '/api/menu-match',
  path: '/api/menu-match',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateCocktailImageRoute =
  ApiGenerateCocktailImageRouteImport.update({
    id: '/api/generate-cocktail-image',
    path: '/api/generate-cocktail-image',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGenerateCocktailRoute = ApiGenerateCocktailRouteImport.update({
  id: '/api/generate-cocktail',
  path: '/api/generate-cocktail',
  getParentRoute: () => rootRouteImport,
} as any)
const MMerchantSlugMenuSlugRoute = MMerchantSlugMenuSlugRouteImport.update({
  id: '/m/$merchantSlug/$menuSlug',
  path: '/m/$merchantSlug/$menuSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/gallery': typeof GalleryRoute
  '/mood-input': typeof MoodInputRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/generate-cocktail': typeof ApiGenerateCocktailRoute
  '/api/generate-cocktail-image': typeof ApiGenerateCocktailImageRoute
  '/api/menu-match': typeof ApiMenuMatchRoute
  '/drinks/$id': typeof DrinksIdRoute
  '/guides/mood-cocktail-recipes': typeof GuidesMoodCocktailRecipesRoute
  '/manage/$privateToken': typeof ManagePrivateTokenRoute
  '/restaurant/$id': typeof RestaurantIdRoute
  '/restaurants/double-chicken-please': typeof RestaurantsDoubleChickenPleaseRoute
  '/m/$merchantSlug/$menuSlug': typeof MMerchantSlugMenuSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/gallery': typeof GalleryRoute
  '/mood-input': typeof MoodInputRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/generate-cocktail': typeof ApiGenerateCocktailRoute
  '/api/generate-cocktail-image': typeof ApiGenerateCocktailImageRoute
  '/api/menu-match': typeof ApiMenuMatchRoute
  '/drinks/$id': typeof DrinksIdRoute
  '/guides/mood-cocktail-recipes': typeof GuidesMoodCocktailRecipesRoute
  '/manage/$privateToken': typeof ManagePrivateTokenRoute
  '/restaurant/$id': typeof RestaurantIdRoute
  '/restaurants/double-chicken-please': typeof RestaurantsDoubleChickenPleaseRoute
  '/m/$merchantSlug/$menuSlug': typeof MMerchantSlugMenuSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/gallery': typeof GalleryRoute
  '/mood-input': typeof MoodInputRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/generate-cocktail': typeof ApiGenerateCocktailRoute
  '/api/generate-cocktail-image': typeof ApiGenerateCocktailImageRoute
  '/api/menu-match': typeof ApiMenuMatchRoute
  '/drinks/$id': typeof DrinksIdRoute
  '/guides/mood-cocktail-recipes': typeof GuidesMoodCocktailRecipesRoute
  '/manage/$privateToken': typeof ManagePrivateTokenRoute
  '/restaurant/$id': typeof RestaurantIdRoute
  '/restaurants/double-chicken-please': typeof RestaurantsDoubleChickenPleaseRoute
  '/m/$merchantSlug/$menuSlug': typeof MMerchantSlugMenuSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/gallery'
    | '/mood-input'
    | '/sitemap.xml'
    | '/api/generate-cocktail'
    | '/api/generate-cocktail-image'
    | '/api/menu-match'
    | '/drinks/$id'
    | '/guides/mood-cocktail-recipes'
    | '/manage/$privateToken'
    | '/restaurant/$id'
    | '/restaurants/double-chicken-please'
    | '/m/$merchantSlug/$menuSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/gallery'
    | '/mood-input'
    | '/sitemap.xml'
    | '/api/generate-cocktail'
    | '/api/generate-cocktail-image'
    | '/api/menu-match'
    | '/drinks/$id'
    | '/guides/mood-cocktail-recipes'
    | '/manage/$privateToken'
    | '/restaurant/$id'
    | '/restaurants/double-chicken-please'
    | '/m/$merchantSlug/$menuSlug'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/gallery'
    | '/mood-input'
    | '/sitemap.xml'
    | '/api/generate-cocktail'
    | '/api/generate-cocktail-image'
    | '/api/menu-match'
    | '/drinks/$id'
    | '/guides/mood-cocktail-recipes'
    | '/manage/$privateToken'
    | '/restaurant/$id'
    | '/restaurants/double-chicken-please'
    | '/m/$merchantSlug/$menuSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  GalleryRoute: typeof GalleryRoute
  MoodInputRoute: typeof MoodInputRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiGenerateCocktailRoute: typeof ApiGenerateCocktailRoute
  ApiGenerateCocktailImageRoute: typeof ApiGenerateCocktailImageRoute
  ApiMenuMatchRoute: typeof ApiMenuMatchRoute
  DrinksIdRoute: typeof DrinksIdRoute
  GuidesMoodCocktailRecipesRoute: typeof GuidesMoodCocktailRecipesRoute
  ManagePrivateTokenRoute: typeof ManagePrivateTokenRoute
  RestaurantIdRoute: typeof RestaurantIdRoute
  RestaurantsDoubleChickenPleaseRoute: typeof RestaurantsDoubleChickenPleaseRoute
  MMerchantSlugMenuSlugRoute: typeof MMerchantSlugMenuSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mood-input': {
      id: '/mood-input'
      path: '/mood-input'
      fullPath: '/mood-input'
      preLoaderRoute: typeof MoodInputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants/double-chicken-please': {
      id: '/restaurants/double-chicken-please'
      path: '/restaurants/double-chicken-please'
      fullPath: '/restaurants/double-chicken-please'
      preLoaderRoute: typeof RestaurantsDoubleChickenPleaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/$id': {
      id: '/restaurant/$id'
      path: '/restaurant/$id'
      fullPath: '/restaurant/$id'
      preLoaderRoute: typeof RestaurantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/$privateToken': {
      id: '/manage/$privateToken'
      path: '/manage/$privateToken'
      fullPath: '/manage/$privateToken'
      preLoaderRoute: typeof ManagePrivateTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/mood-cocktail-recipes': {
      id: '/guides/mood-cocktail-recipes'
      path: '/guides/mood-cocktail-recipes'
      fullPath: '/guides/mood-cocktail-recipes'
      preLoaderRoute: typeof GuidesMoodCocktailRecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drinks/$id': {
      id: '/drinks/$id'
      path: '/drinks/$id'
      fullPath: '/drinks/$id'
      preLoaderRoute: typeof DrinksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/menu-match': {
      id: '/api/menu-match'
      path: '/api/menu-match'
      fullPath: '/api/menu-match'
      preLoaderRoute: typeof ApiMenuMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-cocktail-image': {
      id: '/api/generate-cocktail-image'
      path: '/api/generate-cocktail-image'
      fullPath: '/api/generate-cocktail-image'
      preLoaderRoute: typeof ApiGenerateCocktailImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-cocktail': {
      id: '/api/generate-cocktail'
      path: '/api/generate-cocktail'
      fullPath: '/api/generate-cocktail'
      preLoaderRoute: typeof ApiGenerateCocktailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$merchantSlug/$menuSlug': {
      id: '/m/$merchantSlug/$menuSlug'
      path: '/m/$merchantSlug/$menuSlug'
      fullPath: '/m/$merchantSlug/$menuSlug'
      preLoaderRoute: typeof MMerchantSlugMenuSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  GalleryRoute: GalleryRoute,
  MoodInputRoute: MoodInputRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiGenerateCocktailRoute: ApiGenerateCocktailRoute,
  ApiGenerateCocktailImageRoute: ApiGenerateCocktailImageRoute,
  ApiMenuMatchRoute: ApiMenuMatchRoute,
  DrinksIdRoute: DrinksIdRoute,
  GuidesMoodCocktailRecipesRoute: GuidesMoodCocktailRecipesRoute,
  ManagePrivateTokenRoute: ManagePrivateTokenRoute,
  RestaurantIdRoute: RestaurantIdRoute,
  RestaurantsDoubleChickenPleaseRoute: RestaurantsDoubleChickenPleaseRoute,
  MMerchantSlugMenuSlugRoute: MMerchantSlugMenuSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
